GET https://w837psavk9.execute-api.us-east-1.amazonaws.com/prod/spaces
###
GET https://hz1p3z53e4.execute-api.us-east-1.amazonaws.com/prod/sdkspaces
###
POST https://hz1p3z53e4.execute-api.us-east-1.amazonaws.com/prod/sdkspaces
Content-Type: application/json

{
    "location": "Dallas"
}
###
PUT https://hz1p3z53e4.execute-api.us-east-1.amazonaws.com/prod/sdkspaces?id=080cfa54-cb9f-4214-9377-c9f4e3fbd86d
Content-Type: application/json

{
    "location": "Delhi2"
}
###

DELETE  https://hz1p3z53e4.execute-api.us-east-1.amazonaws.com/prod/sdkspaces?id=080cfa54-cb9f-4214-9377-c9f4e3fbd86d
###

GET https://w837psavk9.execute-api.us-east-1.amazonaws.com/prod/sdkspaces?id=343345
###